---
- name: Include CA recipes
  include: ca.yml

- name: Create custom Diffie-Hellman parameters
  shell: "openssl dhparam -out {{ INDIGOVR_CERT_DIR }}/dh2048.pem 2048"
  args:
    creates: "{{ INDIGOVR_CERT_DIR }}/dh2048.pem"
  notify:
    -  Enable and start OpenVPN service

- name: Copy CRL to OpenVPN
  copy:
    src: "{{ INDIGOVR_CA_DIR }}/crl.pem"
    dest: "{{ INDIGOVR_CERT_DIR }}/crl.pem"
  notify:
    -  Enable and start OpenVPN service

- name: Copy CA certificate to OpenVPN
  copy:
    src: "{{ INDIGOVR_CA_DIR }}/ca.crt"
    dest: "{{ INDIGOVR_CERT_DIR }}/ca.crt"
  notify:
    -  Enable and start OpenVPN service

- name: Create client configuration directory
  file:
    path: /etc/openvpn/ccd
    state: directory
    mode: 0700
    owner: root
    group: root
  notify:
    -  Enable and start OpenVPN service

- name: CSR
  include: openssl_csr.yml

- name: Copy CSR to CA
  copy:
    src: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.csr"
    dest: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr"

- name: Sign certificate
  shell: openssl ca -config "{{ INDIGOVR_CA_DIR }}/openssl.cnf" -extensions server -days 365 -notext -batch -md sha512 -in "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr" -out "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
  args:
    creates: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"


- name: Copy certificate to OpenVPN
  copy:
    src: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
    dest: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.crt"
  notify:
    -  Enable and start OpenVPN service

