---
- name: Include CentOS recipes
  include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Include OpenVPN recipes
  include: openvpn.yml

- name: Include "{{INDIGOVR_NODE_TYPE}}" recipe
  include: "{{INDIGOVR_NODE_TYPE}}.yml"
