- name: Install OpenVPN package
  package:
    name: openvpn
    state: present
  notify:
    - Enable and start OpenVPN service

- name: "Create {{ INDIGOVR_USER }} user"
  user:
    name: "{{ INDIGOVR_USER }}"
    state: present

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_set: yes
  when:
    - ansible_virtualization_type != "docker"
    - INDIGOVR_NODE_TYPE != "standalone"

- name: Create certs directory
  file:
    path: /etc/openvpn/certs
    state: directory
    mode: 0750
    owner: root
    group: "{{ INDIGOVR_USER }}"

- name: Copy OpenVPN configuration
  template:
    src: "{{ INDIGOVR_NODE_TYPE }}.conf.j2"
    dest: "/etc/openvpn/{{ INDIGOVR_NODE_TYPE }}.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - Enable and start OpenVPN service
